# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd9d420528ac57e3cf755211581d5bfb8f83d7c1d0f90e401e99f9e251a46eefb4b5e0f6636291f95a7352e2bf6e2494c2dca2bb1c27464b7d37262d8848add

test:
  secret_key_base: ea8ef906ce72a0d70509cc2ab5818094825c28caa2d770c63c6f770b8d05253a9217e7a5dc2a157e022257ef62f21e86a0bfb0db4e0adf0a1157177a0cf26177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
